global:
  scrape_interval:     15s 

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:

  - job_name: 'docker'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9786']
  
  - job_name: 'nodeexport'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'docker c advisor'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:8080']
